baseURL = 'https://jkstack.github.io/'
languageCode = 'zh-cn'
title = '精鲲开源项目文档'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
